[package]
name = "zergc"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { workspace = true }
ast = { workspace = true }
clap = { version = "4.5.60", features = ["derive"] }
backend = { workspace = true }
