[workspace]
resolver = "3"
members = ["ast", "backend","parser", "typechecker","zergc"]

[workspace.dependencies]
ast = { path = "./ast" }
parser = { path = "./parser" }
typechecker = { path = "./typechecker" }
backend = { path = "./backend" }
